댓글 - nickname 추가
프로젝트- 참가인원 추가
프로젝트- 작성자 추가

TRUNCATE TABLE TBL_PROJECT;
TRUNCATE TABLE TBL_PROJECT_FILE;

ALTER TABLE TBL_REPLY ADD NICKNAME VARCHAR2(1000) NULL;
ALTER TABLE TBL_PROJECT ADD APPLY_COUNT NUMBER DEFAULT 0;
ALTER TABLE TBL_PROJECT ADD USER_NUMBER NUMBER;