CREATE TABLE TBL_USER (
    USER_NUMBER	NUMBER PRIMARY KEY,
	USER_EMAIL	VARCHAR2(1000) NOT NULL,
	USER_NAME	VARCHAR2(1000) NOT NULL,
	USER_NICKNAME	VARCHAR2(1000) NOT NULL,
	USER_PASSWORD	VARCHAR2(1000) NOT NULL,
	USER_CONTENT	VARCHAR2(1000),
	USER_STATUS	NUMBER(3) DEFAULT 0,
	USER_KAKAO	VARCHAR2(1000),
	USER_REGISTER_DATE DATE DEFAULT SYSDATE,
	ACHIEVEMENT_NUMBER	NUMBER
);

CREATE TABLE TBL_USER_FILE (
    USER_FILE_UUID VARCHAR2(1000) PRIMARY KEY,
   	USER_FILE_UPLOAD_PATH VARCHAR2(1000) NOT NULL,
   	USER_FILE_NAME VARCHAR2(2000) NOT NULL,
   	USER_FILE_IMAGE CHAR(1),
   	USER_NUMBER	NUMBER,
   	CONSTRAINT FK_FILE_USER_NUMBER FOREIGN KEY(USER_NUMBER)
   	REFERENCES TBL_USER(USER_NUMBER) ON DELETE CASCADE
);



CREATE TABLE TBL_PROJECT (
    PROJECT_NUMBER	NUMBER PRIMARY KEY,
	PROJECT_TITLE	VARCHAR2(1000) NOT NULL,
	PROJECT_CATEGORY	VARCHAR2(1000) NOT NULL,
	PROJECT_CONTENT	VARCHAR2(4000) NOT NULL,
	PROJECT_AUTHENTICATION	VARCHAR2(4000) NOT NULL,
	PROJECT_START_DATE	DATE DEFAULT SYSDATE,
	PROJECT_END_DATE	DATE DEFAULT SYSDATE,
	PROJECT_PHOTO VARCHAR2(1000),
	PROJECT_STATUS NUMBER(3) DEFAULT 0
);

CREATE TABLE TBL_PROJECT_FILE(
   	PROJECT_FILE_UUID VARCHAR2(1000) PRIMARY KEY,
   	PROJECT_FILE_UPLOAD_PATH VARCHAR2(1000) NOT NULL,
   	PROJECT_FILE_NAME VARCHAR2(2000) NOT NULL,
   	PROJECT_FILE_IMAGE CHAR(1),
   	PROJECT_NUMBER	NUMBER,
   	CONSTRAINT FK_FILE_PROJECT_NUMBER FOREIGN KEY(PROJECT_NUMBER)
   	REFERENCES TBL_PROJECT(PROJECT_NUMBER) ON DELETE CASCADE
   );
  
  CREATE TABLE TBL_REVIEW(
   	REVIEW_NUMBER	NUMBER PRIMARY KEY,
	USER_NUMBER	NUMBER NOT NULL,
	PROJECT_NUMBER	NUMBER NOT NULL,
	REVIEW_CONTENT	VARCHAR2(4000) NOT NULL,
	REVIEW_REGISTER_DATE DATE DEFAULT SYSDATE,
   	CONSTRAINT FK_REIVEW_PROJECT_NUMBER FOREIGN KEY(PROJECT_NUMBER)
   	REFERENCES TBL_PROJECT(PROJECT_NUMBER) ON DELETE CASCADE,
   	CONSTRAINT FK_REIVEW_USER_NUMBER FOREIGN KEY(USER_NUMBER)
   	REFERENCES TBL_USER(USER_NUMBER) ON DELETE CASCADE
   );
  
    CREATE TABLE TBL_PARTICIPATION(
   	PROJECT_NUMBER	NUMBER,
	USER_NUMBER	NUMBER,
	PARTICIPATION_STATUS	NUMBER(3) NOT NULL,
	PARTICIPATION_REGISTER_DATE	DATE DEFAULT SYSDATE,
   	CONSTRAINT FK_PAR_PROJECT_NUMBER FOREIGN KEY(PROJECT_NUMBER)
   	REFERENCES TBL_PROJECT(PROJECT_NUMBER) ON DELETE CASCADE,
   	CONSTRAINT FK_PAR_USER_NUMBER FOREIGN KEY(USER_NUMBER)
   	REFERENCES TBL_USER(USER_NUMBER) ON DELETE CASCADE,
   	CONSTRAINT PARTICIPATION_PK PRIMARY KEY(PROJECT_NUMBER, USER_NUMBER)
   );
  
  CREATE TABLE TBL_LIKE(
   	REVIEW_NUMBER	NUMBER NOT NULL,
	USER_NUMBER	NUMBER NOT NULL,
   	CONSTRAINT FK_LIKE_REVIEW_NUMBER FOREIGN KEY(REVIEW_NUMBER)
   	REFERENCES TBL_REVIEW(REVIEW_NUMBER) ON DELETE CASCADE,
   	CONSTRAINT FK_LIKE_USER_NUMBER FOREIGN KEY(USER_NUMBER)
   	REFERENCES TBL_USER(USER_NUMBER) ON DELETE CASCADE,
   	CONSTRAINT LIKE_PK PRIMARY KEY(REVIEW_NUMBER, USER_NUMBER)
   );
  
  CREATE TABLE TBL_REVIEW_FILE(
   	REVIEW_FILE_UUID VARCHAR2(1000) PRIMARY KEY,
   	REVIEW_FILE_UPLOAD_PATH VARCHAR2(1000) NOT NULL,
   	REVIEW_FILE_NAME VARCHAR2(2000) NOT NULL,
   	REVIEW_FILE_IMAGE CHAR(1),
   	REVIEW_NUMBER	NUMBER,
   	CONSTRAINT FK_FILE_REVIEW_NUMBER FOREIGN KEY(REVIEW_NUMBER)
   	REFERENCES TBL_REVIEW(REVIEW_NUMBER) ON DELETE CASCADE
   );
  
   CREATE TABLE TBL_REPLY(
   	REPLY_NUMBER	NUMBER PRIMARY KEY,
	REVIEW_NUMBER	NUMBER NOT NULL,
	USER_NUMBER	NUMBER NOT NULL,
	REPLY_CONTENT VARCHAR2(4000) NOT NULL,
	REPLY_REGISTER_DATE DATE DEFAULT SYSDATE,
   	CONSTRAINT FK_REPLY_REVIEW_NUMBER FOREIGN KEY(REVIEW_NUMBER)
   	REFERENCES TBL_REVIEW(REVIEW_NUMBER) ON DELETE CASCADE,
   	CONSTRAINT FK_REPLY_USER_NUMBER FOREIGN KEY(USER_NUMBER)
   	REFERENCES TBL_USER(USER_NUMBER) ON DELETE CASCADE
   );
  
  
  CREATE TABLE TBL_REPORT(
	REPORT_NUMBER	NUMBER PRIMARY KEY,
	USER_NUMBER	NUMBER NOT NULL,
	REVIEW_NUMBER	NUMBER NOT NULL,
	REPORT_REASON	VARCHAR2(1000) NOT NULL,    
   	CONSTRAINT FK_REPORT_REVIEW_NUMBER FOREIGN KEY(REVIEW_NUMBER)
   	REFERENCES TBL_REVIEW(REVIEW_NUMBER) ON DELETE CASCADE,
   	CONSTRAINT FK_REPORT_USER_NUMBER FOREIGN KEY(USER_NUMBER)
   	REFERENCES TBL_USER(USER_NUMBER) ON DELETE CASCADE
   );
  
  CREATE TABLE TBL_MESSAGE(
   	SEND_USER_NUMBER	NUMBER NOT NULL,
	RECEIVE_USER_NUMBER	NUMBER NOT NULL,
	MESSAGE_ROOM	VARCHAR2(1000),
	MESSAGE_CONTENT	VARCHAR2(1000) NOT NULL,
	MESSAGE_DATE	DATE	DEFAULT	SYSDATE,	
   	CONSTRAINT FK_MESSAGE_SEND_NUMBER FOREIGN KEY(SEND_USER_NUMBER)
   	REFERENCES TBL_USER(USER_NUMBER) ON DELETE CASCADE,
   	CONSTRAINT FK_MESSAGE_RECEIVE_NUMBER FOREIGN KEY(RECEIVE_USER_NUMBER)
   	REFERENCES TBL_USER(USER_NUMBER) ON DELETE CASCADE,
   	CONSTRAINT MESSAGE_PK PRIMARY KEY(SEND_USER_NUMBER, RECEIVE_USER_NUMBER)
   );
  
  CREATE TABLE TBL_FOLLOW(
   	FOLLOWING_NUMBER	NUMBER NOT NULL,
	FOLLOWER_NUMBER	NUMBER NOT NULL,
   	CONSTRAINT FK_FOLLOW_FOLLOWING_NUMBER FOREIGN KEY(FOLLOWING_NUMBER)
   	REFERENCES TBL_USER(USER_NUMBER) ON DELETE CASCADE,
   	CONSTRAINT FK_FOLLOW_FOLLOWER_NUMBER FOREIGN KEY(FOLLOWER_NUMBER)
   	REFERENCES TBL_USER(USER_NUMBER) ON DELETE CASCADE,
   	CONSTRAINT FOLLOW_PK PRIMARY KEY(FOLLOWING_NUMBER, FOLLOWER_NUMBER)
   );
  
  CREATE TABLE TBL_ACHIEVEMENT(
   	ACHIEVEMENT_NUMBER	NUMBER PRIMARY KEY,
	USER_NUMBER	NUMBER NOT NULL,
	ACHIEVEMENT_MEDAL	VARCHAR2(1000),
   	CONSTRAINT FK_ACHIEVEMENT_USER_NUMBER FOREIGN KEY(USER_NUMBER)
   	REFERENCES TBL_USER(USER_NUMBER) ON DELETE CASCADE
   );
  
  
  
  
