INSERT INTO TBL_USER
(USER_NUMBER, EMAIL, NAME, NICKNAME, PASSWORD)
VALUES(SEQ_BOARD.NEXTVAL, 'test12', 'teste1', 'teste33', '1234');





INSERT INTO TBL_ACHIEVEMENT
(ACHIEVEMENT_NUMBER, USER_NUMBER, MEDAL)
VALUES(SEQ_ACHIEVEMENT.NEXTVAL, 621, 'TESTMEDAL');