INSERT INTO TBL_USER
(USER_NUMBER, EMAIL, NAME, NICKNAME, PASSWORD)
VALUES(SEQ_BOARD.NEXTVAL, 'test12', 'teste1', 'teste33', '1234');





INSERT INTO TBL_ACHIEVEMENT
(ACHIEVEMENT_NUMBER, USER_NUMBER, MEDAL)
VALUES(SEQ_ACHIEVEMENT.NEXTVAL, 621, 'TESTMEDAL');


            SELECT SEQ_PROJECT.NEXTVAL FROM DUAL

        INSERT INTO TBL_PROJECT
        (PROJECT_NUMBER, TITLE, CATEGORY, CONTENT, AUTHENTICATION, START_DATE, END_DATE)
        VALUES(SEQ_PROJECT.NEXTVAL, #{title}, #{category}, #{content}, #{authentication}, #{startDate}, #{endDate})
        
        INSERT INTO TBL_PROJECT
(PROJECT_NUMBER, TITLE, CATEGORY, CONTENT, AUTHENTICATION)
VALUES(SEQ_PROJECT.NEXTVAL, 'test', 'test', 'test', 'teset');

SELECT PROJECT_NUMBER, TITLE, CATEGORY, CONTENT, AUTHENTICATION, START_DATE, END_DATE, STATUS
FROM TBL_PROJECT;

